- hosts: webservers

  tasks:
    - name: install nginx
      apt: name=nginx state=latest
      notify: restart_nginx

    - name: copy html file to nginx root
      copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
        mode: '0644'

    - name: copy nginx config
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart_nginx

  handlers:
    - name: restart_nginx
      service:
        name: nginx
        state: restarted