- hosts: webservers

  tasks:
    - name: install git
      apt: name=git state=present update_cache=yes
      become: yes

    - name: delete git
      apt: name=git state=absent
      become: yes